### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by tristanwietsma** [balbeko/hubot-jenkins#2]
When calling `jenkins describe`, I get the following traceback:

``` code
[Thu Jun 11 2015 19:38:38 GMT+0000 (UTC)] ERROR TypeError: undefined is not a function
  at Connector.module.exports.Connector.message (/home/bot/node_modules/hubot-hipchat/src/connector.coffee:230:5, <js>:221:25)
  at HipChat.send (/home/bot/node_modules/hubot-hipchat/src/hipchat.coffee:35:7, <js>:50:38)
  at Response.send (/home/bot/node_modules/hubot/src/response.coffee:22:5, <js>:20:47)
  at /home/bot/node_modules/hubot-jenkins/src/jenkins.coffee:203:13, <js>:212:22
  at IncomingMessage.<anonymous> (/home/bot/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

Any thoughts?

**Comment by tristanwietsma** [comment]
looks like it was credentials; my bad.
